### ISSUE TITLE
Setting AWS Credentials 

### ISSUE THREAD

**Issue by ep4sh** [PayU/fluentBit-sqs-plugin#4]
Hi there!
Would this plugin require the explicit setting of AWS credentials via environment variables or it can pick temporary ones with AWS IAM roles?

**Comment by shyimo** [comment]
@ep4sh Hi.
You can explicit use AWS credentials if you want. but if the plugin wont found any he will search IAM role on the host automatically.

More info can be found on the readme:
https://github.com/PayU/fluentBit-sqs-plugin#special-notes

**Comment by ep4sh** [comment]
@shyimo hi thanks a lot for your answer, I missed these notes, but now I see =)
It's what I exactly need
